linuxdeepin/deepin-editor

src/utils.cpp

feat: support Greek
https://github.com/linuxdeepin/developer-center/issues/957
Change-Id: Ie7bcbf16265509229b6bc2c5d2dd84b52e3bda7c

refactor: optimize the logic of text encoding probing

---

src/dtextedit.cpp
src/dtextedit.h
src/widgets/bottombar.cpp
src/widgets/bottombar.h

feat: display word count from status bar

---

src/dtextedit.cpp
src/settingsdialog.cpp
translations/deepin-editor.ts

https://github.com/linuxdeepin/internal-discussion/issues/1269

chore: translation update.

---

src/startmanager.cpp

https://bbs.deepin.org/forum.php?mod=viewthread&tid=179118
taskID=5801

fix: should call showNormal() to raise window

---

src/common/eventlogutils.cpp
src/common/eventlogutils.h
src/main.cpp

Description: 提交埋点需求，采集文本编辑器启动数据
Log: 提交埋点需求，采集文本编辑器启动数据

feat: 提交埋点需求，采集文本编辑器启动数据

---

src/encodes/detectcode.cpp
tests/src/encodes/ut_detectcode.cpp

Description: 使用查找unicode中文字符二次截断的方式仍有概率存在截断字符，导致编码格式识别错误。 修改文本编码识别策略，针对大文本文件读取场景，在低识别率时截断尾部字符并再次判断编码格式，直到较高的编码识别率，普通场景下的重复判断不会超过三次。 添加多种编码、错误场景下的UT。
Log: 修复文本编码识别错误，在特定场景显示乱码问题
Bug: https://pms.uniontech.com/bug-view-159471.html
Influence: 文本编码解析

fix: 修复文本编码识别错误，在特定场景显示乱码问题

---

src/controls/tabbar.cpp
tests/src/controls/ut_jumplinebar.cpp
tests/src/widgets/ut_window.cpp

Description: 修复报错的单元测试用例，调整部分开发过程中修改功能对应的单元测试用例。
Log: 修复单元测试报错
Bug: https://pms.uniontech.com/bug-view-123253.html
Influence: 单元测试

fix: 修复单元测试报错

---

src/widgets/window.cpp
src/widgets/window.h

Description: 使用windowtitle设置路径和文件名，使用xwininfo命令获取当前窗体正在操作文件名和路径
Log: 使用windowtitle设置窗口路径和文件名

feat: 使用windowtitle设置窗口路径和文件名

---

src/widgets/window.cpp

Description:
原因是在关闭文本编辑器窗口时，会触发使用 QProcess::startDetached() 关闭 dbus 服务，会使用 fork() 创建子进程，在使用 fork() 创建子进程时，会保留除文件锁外的锁状态。而关闭窗口会触发 DSettings 的后端(位于子线程)同步配置，同步时会对静态的 environmentMutex 加锁。二者同时进行时，有概率导致锁状态保留，在子进程中无法释放，依赖子进程消息的主进程同样陷入阻塞状态，导致有概率在窗口关闭时出现程序未响应的情况。 
修改方式为在关闭窗口等更新配置的操作时，修改QProcess为同步处理，且优先同步配置。
Log: 修复当频繁打开关闭文本编辑器时，或关闭窗口时，文本编辑器无响应问题
Bug: https://pms.uniontech.com/bug-view-113403.html
Influence: 程序关闭时的未响应问题

fix: 修复当频繁打开关闭文本编辑器时，或关闭窗口时，文本编辑器无响应问题

---

src/encodes/detectcode.cpp

Description: 原因是在转换文件编码时，未正确获取转换后文本长度，识别到多字节的'\00'字符时直接截断文本。 修改编码转换后获取文本长度的方式，同时为多字节的UTF-16/UTF-32编码添加BOM信息以提高文本识别率。
Log: 修复切换UTF-16LE编码后保存，文件内容缺失
Bug: https://pms.uniontech.com/bug-view-166089.html
Influence: 文件编码识别和转换

fix: 修复切换UTF-16LE编码后保存，文件内容缺失

---

src/common/utils.cpp
src/common/utils.h
src/editor/dtextedit.cpp
src/widgets/window.cpp

Description: 调整部分修改的DBus接口使用方式，根据版本区分处理V20和V23的接口调用 ActiveWindow接口暂未实现，使用V20接口兼容
Log: 适配V23 DDE DBus接口
Influence: DBus接口

feat: 适配V23 DDE DBus接口

---

src/common/fileloadthread.cpp
src/common/fileloadthread.h
src/controls/warningnotices.cpp
src/controls/warningnotices.h
src/editor/dtextedit.cpp
src/editor/dtextedit.h
src/editor/editwrapper.cpp
src/editor/editwrapper.h
src/encodes/detectcode.cpp
tests/src/common/ut_fileloadthread.cpp
tests/src/editor/ut_editwrapper.cpp
translations/deepin-editor.ts
translations/deepin-editor_es.ts
translations/deepin-editor_zh_CN.ts

合并V20分支bug修复
Log: 合并V20分支bug修复

fix: 合并V20分支bug修复

---

src/common/performancemonitor.cpp
src/editor/deletebackcommond.cpp
src/editor/deletebackcommond.h
src/editor/dtextedit.cpp
src/editor/indenttextcommond.cpp
src/editor/indenttextcommond.h
src/editor/insertblockbytextcommond.cpp
src/editor/insertblockbytextcommond.h
src/editor/replaceallcommond.cpp
src/editor/replaceallcommond.h
src/main.cpp
tests/src/editor/ut_deletebackcommond.cpp
tests/src/editor/ut_insertblockbytextcommond.cpp
tests/src/editor/ut_replaceallcommond.cpp

* Commond -> Command;
* LOG_FLAG is a QString variable, cannot be surrounded by quotes;
* initaalize -> initialize;
* Initialize appenders first to get pretty print;
* Remove some redundant quotes using qPrintable.
Log: correct some typos and improve log

chore: correct some typos and improve log

---

debian/changelog

Update version to 6.0.1
Log: Update version to 6.0.1

Chore: Update version to 6.0.1

---

debian/changelog

Update version to 6.0.2
Log: Update version to 6.0.2

chore: Update version to 6.0.2

---

debian/changelog

Update version to 6.0.5
Log: Update version to 6.0.5
Change-Id: Ia13bd138c7e33792f8a2c80a9d8b2821311f5177

chore: Update version to 6.0.5

---

src/editor/dtextedit.cpp
src/editor/dtextedit.h

Fixes linuxdeepin/developer-center#3667

fix: the preedit has not been displayed

---

src/editor/editwrapper.cpp

对于超长文件，Qt在使用 QSaveFile 保存文件时，若当前环境不支持创建无名文件,
会在相同路径创建临时文件，路径为保存文件名 + 唯一后缀，此临时文件名可能
超过255长度限制，导致保存失败。因此，过长的文件名屏蔽使用QSaveFile。
Log: 修复另存255长度文件名的文件权限不足问题
Bug: https://pms.uniontech.com/bug-view-192375.html
Influence: 长文件名另存

fix: 修复另存255长度文件名的文件权限不足问题

---

src/encodes/detectcode.cpp
src/main.cpp

DLogManager需在依赖部分app信息，需在app构造后初始化
Log: 修复未正确记录日志
Influence: 日志文件

fix: 修复未正确记录日志

---

.tx/config
.tx/deepin.conf
translations/deepin-editor.ts
translations/deepin-editor_az.ts
translations/deepin-editor_ca.ts
translations/deepin-editor_cs.ts
translations/deepin-editor_de.ts
translations/deepin-editor_es.ts
translations/deepin-editor_fi.ts
translations/deepin-editor_fr.ts
translations/deepin-editor_hu.ts
translations/deepin-editor_ms.ts
translations/deepin-editor_nl.ts
translations/deepin-editor_pl.ts
translations/deepin-editor_pt.ts
translations/deepin-editor_pt_BR.ts
translations/deepin-editor_ru.ts
translations/deepin-editor_sq.ts
translations/deepin-editor_ug.ts
translations/deepin-editor_uk.ts
translations/deepin-editor_zh_CN.ts
translations/deepin-editor_zh_HK.ts
translations/deepin-editor_zh_TW.ts

更新翻译配置和翻译文件
* deepin-editor 使用 m20 翻译分支
Log:  更新翻译配置和翻译文件
Influence: 翻译配置 翻译文件

chore: 更新翻译配置和翻译文件

---

translations/deepin-editor_ar.ts
translations/deepin-editor_bg.ts
translations/deepin-editor_bo.ts
translations/deepin-editor_da.ts
translations/deepin-editor_fa.ts
translations/deepin-editor_gl_ES.ts
translations/deepin-editor_hi_IN.ts
translations/deepin-editor_id.ts
translations/deepin-editor_it.ts
translations/deepin-editor_ko.ts
translations/deepin-editor_lt.ts
translations/deepin-editor_ne.ts
translations/deepin-editor_sl.ts
translations/deepin-editor_sr.ts
translations/deepin-editor_tr.ts

更新翻译文件，主要更新藏文翻译
Log: 更新藏文翻译文件
Influence: 翻译文件

chore: 更新藏文翻译文件

---

src/common/utils.cpp

添加 mimetype 类型以支持 mod/toml 文件格式。
Log: 添加 mod/toml 格式支持.
Bug: https://pms.uniontech.com/bug-view-210815.html
Bug: https://pms.uniontech.com/bug-view-212273.html
Influence: SupportFormat

fix: Add support mimetype mod/toml.

---

src/common/settings.cpp
src/common/utils.cpp
src/common/utils.h
src/controls/findbar.cpp
src/controls/findbar.h
src/controls/jumplinebar.cpp
src/controls/jumplinebar.h
src/controls/linebar.cpp
src/controls/replacebar.cpp
src/controls/replacebar.h
src/controls/tabbar.cpp
src/controls/warningnotices.cpp
src/editor/dtextedit.cpp
src/editor/editwrapper.cpp
src/main.cpp
src/widgets/bottombar.cpp
src/widgets/bottombar.h
src/widgets/ddropdownmenu.cpp
src/widgets/pathsettintwgt.cpp
src/widgets/pathsettintwgt.h
src/widgets/window.cpp
src/widgets/window.h

适配紧凑模式,动态调整控件高度和位置.
紧凑模式通过宏 `DTKWIDGET_CLASS_DSizeMode`
在编译期判断是否编译紧凑模式适配代码.
Log: 适配紧凑模式
Task: https://pms.uniontech.com/task-view-292061.html
Influence: UI

feat: adapt compact mode. 

---

src/common/utils.cpp
src/widgets/bottombar.cpp

适配紧凑模式遗漏区分版本兼容宏,
修复低版本DTK下的构建错误.
Log: 修复在低版本DTK的构建错误

fix: Build erorr under low version DTK.

---

src/common/utils.cpp
src/common/utils.h
src/main.cpp

Adapt Treeland, disable wayland settings in
Treeland enviroment.
Update system version check, return V23 if
greater than "23".
Log: Adapt Treeland.
Influence: Wayland

feat: adapt treeland

---

debian/changelog

bump verison to 6.5.0
Log: bump verison to 6.5.0

chore: bump verison to 6.5.0

---

src/basepub/load_libs.c
src/common/utils.cpp
src/main.cpp
tests/src/common/ut_utils.cpp

Optimize startup failure problem
Log: Optimize startup failure problem
Task: https://pms.uniontech.com/task-view-361175.html

fix: Optimize startup failure problem

---

arm64/linglong.yaml
debian/changelog
linglong.yaml

v6.5.2 release.
Log: v6.5.2 release.

chore: new version 6.5.2

---

arm64/linglong.yaml
linglong.yaml

Fix version sync issue while building.
Log: fix linglong sync issue.

fix: Fix linglong version

---

debian/changelog
src/common/utils.cpp
src/common/utils.h
src/main.cpp

remove kwayland-shell env
Log: remove kwayland-shell env

fix: remove kwayland-shell env

---

src/startmanager.cpp
src/startmanager.h
src/widgets/window.cpp

trim release memory
Log:  release memory
Bug: https://pms.uniontech.com/bug-view-282985.html

fix: trim release memory

---

arm64/linglong.yaml
linglong.yaml

update linglong version
Log: update linglong version

chore: update linglong version

---

src/editor/dtextedit.cpp

The previous input method not handle the deletion
operation, implement it.
Log: Adapt input method delete operation
Bug: https://pms.uniontech.com/bug-view-292059.html
Influence: undo-stack

fix: adapt input method delete operation

---

src/controls/tabbar.cpp
src/widgets/window.cpp

remove invalid  url
Log: remove invalid  url

fix: remove invalid  url

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.10
Log: Bump version to 6.5.10

chore: Bump version to 6.5.10

---

src/common/iflytek_ai_assistant.cpp
src/common/iflytek_ai_assistant.h
src/editor/dtextedit.cpp
src/editor/dtextedit.h
src/editor/editwrapper.cpp
src/editor/editwrapper.h
src/widgets/window.cpp
src/widgets/window.h
translations/deepin-editor.ts
translations/deepin-editor_zh_CN.ts
translations/deepin-editor_zh_HK.ts
translations/deepin-editor_zh_TW.ts

1. Add guidance when UOS AI is not installed
2. Add audio device status check and error notifications
3. Fix voice reading menu item display when text is selected
4. Optimize error handling for AI assistant features
Changes:
- Add installed() check and error messages for AI features
- Add audio device status validation
- Simplify right-click menu logic for AI actions
- Add warning notifications for AI operation failures
Log: Improve UOS AI assistant integration.
Task: https://pms.uniontech.com/story-view-37693.html,
https://pms.uniontech.com/story-view-37695.html,
https://pms.uniontech.com/story-view-37697.html,
https://pms.uniontech.com/story-view-37691.html

feat: Improve UOS AI assistant integration

---

src/configs/json/org_deepin_editor.hpp

Add a new configuration class for editor settings
Log: add org_deepin_editor configuration class

chore: add org_deepin_editor configuration class

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.12
Log: Bump version to 6.5.12

chore: Bump version to 6.5.12

---

src/common/iflytekaiassistantthread.cpp

As title, try get introspect when not detect
ai service registered.
Log: Fixed the right-click menu not having AI options.
Bug: https://pms.uniontech.com/bug-view-300223.html

fix: not detect ai service registered.

---

src/common/iflytek_ai_assistant.cpp
src/common/iflytek_ai_assistant.h
src/common/utils.cpp

As title.
Log: Fixed a crash issue and disable stop tss on close.
Bug: https://pms.uniontech.com/bug-view-301561.html

fix: toast may cuase crash and disable stop tts

---

arm64/linglong.yaml
debian/changelog
install_dep
linglong.yaml
loong64/linglong.yaml

Update linglong.yaml for qt6.8 runtime.
Log: Update linglong.yaml for qt6.8 runtime

chore: update linglong.yaml for qt6.8 runtime

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.18
Log: Bump version to 6.5.18

chore: Bump version to 6.5.18

---

src/common/urlinfo.h
src/startmanager.cpp
src/widgets/window.cpp

As title.
Log: use canonical file path.
Bug: https://pms.uniontech.com/zentao/bug-view-297679.html

fix: use canonical file path

---

src/common/text_file_saver.cpp
src/common/text_file_saver.h
src/editor/editwrapper.cpp

-- Add logic to replace '\n' to "\r\n" when at windows end line format.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-328591.html

Fix: [EndLineFormat] The windows end line format error.
