.gitignore, src/startmanager.cpp
If the main window is minimized, open new files should bring the
main window to the front end, not just open files in the background.
=> fix: activate window when opening files

src/window.cpp
使用编辑器打开文件时，文件管理器默认打开是文档目录
手动选择目录后，记录上次选择的目录
额外：当记住的上次选择的位置不存在或文档目录本身不存在时，会 fallback 到家目录。
=> feat: set default open dir as QStandardPaths::DocumentsLocation

src/editwrapper.cpp, src/editwrapper.h, src/widgets/bottombar.cpp, src/window.cpp
Reproduce steps:
- Try use deepin-editor save file under a non-DDE enviroment (tested under Mate)
- a native (**not** dde-file-manager) file dialog opened up, enter any file name.
- deepin-editor crashes.
=> fix: crash if DDE file select dialog is not available to use

src/dtextedit.cpp
Fix Qt's cursor flash time setting does not take effect
https://github.com/linuxdeepin/qt5dxcb-plugin/pull/23
修复光标闪动速度的设置不生效
=> fix: do not overwrite the cursorFlashTime of QGuiApplication

src/dtextedit.cpp
```
warning: 'width' is deprecated: Use QFontMetrics::horizontalAdvance
qfontmetrics.h:109:5: note: 'width' has been explicitly marked deprecated here
qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
qcompilerdetection.h:675:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
```
=> fix: width -> horizontalAdvance

.packit.yaml, rpm/deepin-editor.spec
This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
=> feat: Initial packit setup

src/editor/dtextedit.cpp, src/widgets/window.cpp, src/widgets/window.h
Description: 右键弹出菜单，会通过dbus获取语音助手各接口状态，频繁右键弹出菜单，某个时刻会导致应用获取不到语音助手返回结果，主线程会一直等待，导致主线程卡死。
Log: 偶现点击切换编码按钮后，应用卡死
Bug: https://pms.uniontech.com/bug-view-143259.html
=> fix: 偶现点击切换编码按钮后，应用卡死

src/editor/editwrapper.h, src/widgets/window.cpp, src/widgets/window.h, tests/src/widgets/ut_window.cpp
Description: 大文本打印时，文本拷贝、布局和高亮耗时长，计算时占用主线程，导致文本编辑器卡死。修改文本拷贝、布局和高亮的计算方式，将计算步骤拆分为单独的子步骤，使用QApplication::processEvents处理其它事件。界面不再卡死，对超过100MB的文本文件有效支持。对需要高亮的代码文件需要进一步优化高亮处理效率。
Log: 修复133M的文本文件，点击打印没有反应文本编辑器卡死
Bug: https://pms.uniontech.com/bug-view-143359.html
Influence: 文档打印
=> fix: 修复133M的文本文件，点击打印没有反应文本编辑器卡死

src/editor/deletebackcommond.cpp, src/editor/deletetextundocommand.cpp, src/editor/deletetextundocommand.h, src/editor/dtextedit.cpp, src/editor/inserttextundocommand.cpp, src/editor/inserttextundocommand.h, tests/src/editor/ut_deletetextundocommand.cpp, tests/src/editor/ut_inserttextundocommand.cpp
Description: 旧版代码在进行撤销恢复时未将光标位置复位，在撤销项执行撤销恢复时将光标位置同样进行恢复。
Log: 修复撤销时改变光标的位置后继续撤销,光标未移回要撤销的位置
Bug: https://pms.uniontech.com/bug-view-115027.html
Influence: 撤销恢复
=> fix: 修复撤销时改变光标的位置后继续撤销,光标未移回要撤销的位置

src/editor/dtextedit.cpp, src/editor/dtextedit.h
Description: 旧版代码在计算代码括号匹配区域时未能正确过滤代码文本中的字符串内容，添加过滤字符串内容的代码，将重复的代码重构为单个接口。
Log: 修复对需折叠的代码块判断不准确和对代码中括号的匹配不准确问题
Bug: https://pms.uniontech.com/bug-view-138113.html, https://pms.uniontech.com/bug-view-138997.html
Influence: 代码高亮 代码折叠
=> fix: 修复对需折叠的代码块判断不准确和对代码中括号的匹配不准确问题

src/common/utils.cpp
Description: 使用小键盘时，组合键包含"Num"标识，旧版代码未处理导致不能识别小键盘快捷键，添加相应处理。
Log: 修复在文本编辑器设置中使用小键盘中的按键组合编辑快捷键，新设置的快捷键无效
Bug: https://pms.uniontech.com/bug-view-109339.html
Influence: 快捷键
=> fix: 修复在文本编辑器设置中使用小键盘中的按键组合编辑快捷键，新设置的快捷键无效

src/editor/dtextedit.cpp
Description: 使用全选后，文本编辑器设置的全选标识，在使用左、右按键后，全选标识未被移除，导致黏贴时将全文本替换，显示为黏贴未生效。添加选中状态变更时移除全选标识的代码。
Log: 修复文本编辑器使用快捷键粘贴，第一次粘贴不生效
Bug: https://pms.uniontech.com/bug-view-150301.html
Influence: 黏贴文本
=> fix: 修复文本编辑器使用快捷键粘贴，第一次粘贴不生效

src/editor/dtextedit.cpp
Description: 旧版代码按比例计算书签和代码折叠标志的位置，行号显示在单行中部，当文本行高变更时，两者计算方式不同，导致出现显示位置的差异。修改书签和代码折叠标志的位置计算方式，改为显示在行中部。
Log: 修复书签&代码折叠标志的位置比行号稍高一些
Bug: https://pms.uniontech.com/bug-view-107837.html
Influence: 书签 代码折叠标志
=> fix: 修复书签&代码折叠标志的位置比行号稍高一些

src/common/fileloadthread.cpp, src/common/fileloadthread.h, src/editor/editwrapper.cpp, src/editor/editwrapper.h, tests/src/editor/ut_editwrapper.cpp
Description: 旧版代码处理在页面加载前会将所有的文档数据读取，在读取性能较差的设备上，会持续占用IO通道，导致读取时间过长，界面未加载内容。修改为大文件预先加载文件头内容，防止长时间显示白屏。
Log: 修复在打开大文件的时候，从主菜单打开其他文档时不会及时打开并加载
Bug: https://pms.uniontech.com/bug-view-154903.html
Influence: 文件加载
=> fix: 修复在打开大文件的时候，从主菜单打开其他文档时不会及时打开并加载

src/widgets/window.cpp, src/widgets/window.h
Description: 原因：单行文本加载时布局等计算阻塞主线程，且标签页关闭信号通过Qt::QueuedConnection方式抛出，按键点击事件被阻塞。在阻塞恢复后，事件队列中同时存在多个对同一标签页的关闭事件，导致多个标签页被关闭，窗口同时关闭。部分情况下，删除所有标签页后，访问到不存在的标签内容，窗口崩溃。
修改方式：修改为延迟处理标签页关闭信号，防止单个时刻频繁的调用关闭操作，同时添加边界判断。
Log: 修复文本编辑器打开单行50MB的文档过程中，快速点击标签页关闭按钮会使文本编辑器崩溃
Bug: https://pms.uniontech.com/bug-view-154591.html
Influence: 标签页关闭
=> fix: 修复文本编辑器打开单行50MB的文档过程中，快速点击标签页关闭按钮会使文本编辑器崩溃

src/editor/editwrapper.cpp, src/resources/settings.json, src/startmanager.cpp, src/startmanager.h, src/widgets/window.cpp, tests/src/ut_startmanager.cpp
Description: 旧版代码只记录关闭窗口后缓存的书签信息，关闭标签页后，文件的书签不会被记录。补充书签功能，书签信息根据文件路径进行记录，文件标签页关闭后仍保留，直到文件被删除或移动。
Log: 修复添加书签后关闭文档，再次打开文档后，标记的书签消失
Bug: https://pms.uniontech.com/bug-view-155115.html
Influence: 书签
=> fix: 修复添加书签后关闭文档，再次打开文档后，标记的书签消失

src/controls/jumplinebar.cpp
Description: 问题1: 更新文本内容时将输入框内容清空了；
修改1: 移除清空代码，保留输入换行超过允许范围时清空内容。
问题2: 输入范围默认从1开始，当仅单行文本时，最小值和最大值相同，校验代码出现问题；
修改2: 修改输入范围从0开始，0已被处理不允许首位输入，不影响仅单行的情况。
Log: 修复更换“跳到行”控件后，在“跳到行”框中输入和显示数字有异常
Bug: https://pms.uniontech.com/bug-view-112003.html
Influencei: “跳到行”功能
=> fix: 修复更换“跳到行”控件后，在“跳到行”框中输入和显示数字有异常

src/editor/editwrapper.cpp, src/editor/editwrapper.h, src/widgets/window.cpp, tests/src/editor/ut_editwrapper.cpp
Description: 问题1：保存草稿文件时未正确获取需要删除的标签页文件路径；
修改1：获取保存草稿文件后的文件路径，正确删除标签页。
问题2：遍历删除标签页时未考虑存在部分标签页取消的情况；
修改2：新的处理流程取消后会停止在当前标签页。
Log: 修复多窗口下关闭应用，“保存”草稿文件时引起当前窗口的直接关闭 ； “取消”时焦点未顺移至下个标签页，但会继续弹出保存提示框
Bug: https://pms.uniontech.com/bug-view-129877.html
Influence: 标签页关闭 保存草稿文件
=> fix: 修复多窗口下关闭应用，“保存”草稿文件时引起当前窗口的直接关闭 ； “取消”时焦点未顺移至下个标签页，但会继续弹出保存提示框

src/encodes/detectcode.cpp
Description: 在处理大文件时，会截取前1MB的内容进行文本编码格式解析，当文本截取过程时将中文字符的Unicode码截断导致乱码时，会使得编码解析错误。 修改编码格式解析流程，添加判断存在截断字符的代码，对识别率低于90%的文本进行拆分后二次解析，规避字符截断导致的编码格式解析错误。
Log: 修复编辑大小在30-40W字（实际大小在1-2M间）的中文文本文档，保存后再打开，大概率显示乱码
Bug: https://pms.uniontech.com/bug-view-159471.html
Influence: 文本编码解析
=> fix: 修复编辑大小在30-40W字（实际大小在1-2M间）的中文文本文档，保存后再打开，大概率显示乱码

src/widgets/window.cpp
Description: 查找过程使用“下一个”按钮触发跳转，但未触发滚屏信号，没有立即刷新页面的代码高亮效果。在查询过程跳转后刷新页面的代码高亮效果。
Log: 修复查找过程中，代码着色会消失，需滚动鼠标才能恢复
Bug: https://pms.uniontech.com/bug-view-144323.html
Influence: 代码高亮
=> fix: 修复查找过程中，代码着色会消失，需滚动鼠标才能恢复

src/editor/deletetextundocommand.cpp, src/editor/deletetextundocommand.h
Description: 文件逆序删除后撤销，光标位置变更但仍直接插入数据，导致恢复的数据位置变更，未准确撤回数据。修改为在删除前记录当前光标位置，执行恢复时在删除位置插入恢复数据，以准确恢复数据。
Log: 修复文本中含括号时，对文件多次进行删除操作后，不能准确撤回
Bug: https://pms.uniontech.com/bug-view-140501.html
Influence: 撤销重做
=> fix: 修复文本中含括号时，对文件多次进行删除操作后，不能准确撤回

src/editor/dtextedit.cpp, tests/src/editor/ut_textedit.cpp
Description: 旧版代码在拷贝多行文本时，使用QTextCursor::EndoOfLine移动光标，使得每行文本均插入换行符，文本被分割，使得更新源失败。修改光标移动策略，按原有行结构拷贝。
Log: 修复右键菜单复制文本编辑器中多行源到source.list时，更新源报错
Bug: https://pms.uniontech.com/bug-view-162605.html
Influence: 拷贝多行文本
=> fix: 修复右键菜单复制文本编辑器中多行源到source.list时，更新源报错

src/widgets/window.cpp
Description: 文本编辑器打印时设置的打印文档名仅保留文件名称，无后缀、路径信息。修改为打印文档名包含完整文件路径和文件后缀信息的字符串。
Log: 修复文本编辑器打印时，cups日志jobname字段为文件名，没有文件后缀和路径
Bug: https://pms.uniontech.com/bug-view-163649.html
Influence: 文本打印
=> fix: 修复文本编辑器打印时，cups日志jobname字段为文件名，没有文件后缀和路径

src/editor/dtextedit.cpp, src/editor/dtextedit.h, src/editor/inserttextundocommand.cpp, src/editor/inserttextundocommand.h, tests/src/editor/ut_inserttextundocommand.cpp, tests/src/editor/ut_textedit.cpp
Description: 文本编辑器维护独立的撤销栈结构，鼠标中键黏贴事件没有被压入撤销栈中。添加鼠标中键黏贴撤销项，接收鼠标中键释放事件，判断文本内容变更是否为鼠标中键黏贴，若为则添加文本插入撤销项。
Log: 修复通过鼠标中键进行粘贴的文本，无法撤销的问题
Bug: https://pms.uniontech.com/bug-view-162695.html
Influence: 鼠标中键黏贴
=> fix: 修复通过鼠标中键进行粘贴的文本，无法撤销的问题

src/encodes/detectcode.cpp
Description: 旧版代码在进行文本编码识别时，未对识别准确度进行判断，多字节编码（utf-16、utf-32）可能被识别为单字节编码（utf-8、windows-1252）。添加编码识别准确度判断，在单字节编码识别准确度低时，考虑是否为多字节编码格式。
Log: 修复打开文件默认显示编码格式为WINDOWS-1252，文件显示异常，编码格式改为UTF-16BE显示正常
Bug: https://pms.uniontech.com/bug-view-117927.html
Influence: 编码格式识别
=> fix: 修复打开文件默认显示编码格式为WINDOWS-1252，文件显示异常，编码格式改为UTF-16BE显示正常

src/controls/jumplinebar.cpp, src/controls/jumplinebar.h
Description: 旧版代码设置固定的控件大小，未根据显示文本调整控件宽度。修改为根据翻译文本显示宽度调整“跳到行”控件的显示宽度。
Log: 修复系统语言选择波兰语时，“跳到行”功能显示不全
Bug: https://pms.uniontech.com/bug-view-163143.html
Influence: “跳到行”功能
=> fix: 修复系统语言选择波兰语时，“跳到行”功能显示不全

src/editor/editwrapper.cpp, src/widgets/bottombar.cpp, src/widgets/ddropdownmenu.cpp, src/widgets/ddropdownmenu.h, tests/src/editor/ut_editwrapper.cpp
Description: 在更新编码后使用默认的保存文件路径，没有及时更新待保存的编码格式标志。修改为在保存前更新待保存的文件编码格式，添加相关改动的UT用例。
Log: 修复文本编辑器新建标签页，修改编码格式并输入内容，保存时仍为utf-8格式
Bug: https://pms.uniontech.com/bug-view-169265.html
Influence: 文件保存
=> fix: 修复文本编辑器新建标签页，修改编码格式并输入内容，保存时仍为utf-8格式

src/editor/editwrapper.cpp, src/editor/editwrapper.h, src/widgets/bottombar.cpp, src/widgets/ddropdownmenu.cpp, tests/src/editor/ut_editwrapper.cpp
Description: 原因是缺失切换语法高亮格式后触发高亮变更的处理。添加语法高亮切换信号处理，切换后重新更新当前界面展示的语法高亮效果。
Log: 修复文本编辑器选择语法高亮不能及时生效
Bug: https://pms.uniontech.com/bug-view-163627.html
Influence: 语法高亮
=> fix: 修复文本编辑器选择语法高亮不能及时生效

src/widgets/window.cpp
Description: 原因是初始打印时设置了错误的边距，修改bug时引入。移除设置错误边距的代码。
Log: 修复切换基础设置中的打印机设置时，原页面不展示页码，切换一下页面后才可展示
Bug: https://pms.uniontech.com/bug-view-163917.html
Influence: 文档打印
=> fix: 修复切换基础设置中的打印机设置时，原页面不展示页码，切换一下页面后才可展示

src/controls/tabbar.cpp, src/controls/tabbar.h
Description: 原因是‘&’字符在Qt中被标记为助记符，标记为快捷键的一部分，部分控件不显示'&'，同绘制部分的Qt::TextShowMnemonic标识有关，Qt帮助文档建议为将‘&’替换为“&&”显示。修改方案为涉及标签页显示的文本将‘&’替换为“&&”以正常显示‘&’字符。
Log: 修复文件名称中含有&符打开应用无显示
Bug: https://pms.uniontech.com/bug-view-171007.html
Influence: 标签页
=> fix: 修复文件名称中含有&符打开应用无显示

src/editor/editwrapper.cpp, tests/src/editor/ut_editwrapper.cpp
Description: 原因时清理旧的语法高亮信息时，循环处理中遗漏了对尾行的判断，导致单行文本未正常切换高亮。修改循环处理逻辑，正确清理单行文本的格式信息。
Log: 修复单行文本切换语法高亮不能生效问题
Bug: https://pms.uniontech.com/bug-view-163627.html
Influence: 语法高亮
=> fix: 修复单行文本切换语法高亮不能生效问题

src/widgets/window.cpp
Description: 原因是打印处理在DTK5.4.10版本前后使用宏切换不同分支，修改bug过程中调整了部分代码位置，导致在1030环境编译时遇到变量未定义问题。恢复代码位置，使同时兼容两个分支编译。
Log: 修复修改引入导致1030环境编译报错问题
Influence: 1030环境打印处理编译
=> fix: 修复修改引入导致1030环境编译报错问题

src/editor/dtextedit.cpp, src/editor/dtextedit.h
Description: 文本编辑器使用了自定的撤销栈，未对按住Ctrl拖拽复制文本撤销时，拷贝了多余的文本，导致撤销异常。 修改按住Ctrl状态下的处理逻辑，拷贝状态下不在原文本位置插入用于撤销栈管理的文本。
Log: 修复选中文字结合Ctrl复制文本后，进行撤销操作恢复结果不正确的问题。
Bug: https://pms.uniontech.com/bug-view-172865.html
Influence: 撤销栈
Change-Id: I870679a762487bd3365c9104fe845efe4196ae3e
=> fix: 修复选中文字结合Ctrl复制文本后，进行撤销操作恢复结果不正确的问题。

src/main.cpp, src/startmanager.cpp
Description: 批量打开文件时，判断已打开文件后直接跳出，流程错误。修改判断流程，识别已打开文件后继续判断文件。
Log: 修复多选包含已打开文件的情况下，批量打开功能异常
Bug: https://pms.uniontech.com/bug-view-182217.html
Influence: 批量打开文件
=> fix: 修复多选包含已打开文件的情况下，批量打开功能异常

debian/rules
Application should be processed befored passed to CMake. We just need MAJOR.MINOR.PATCH. APP_VERSION is not used thus we delete it. --parallel args is unnecessary in debhelper-compat 12. Don't use DH_AUTO_ARGS and let dh_auto judge what kind of build system to use. Currently we only have CMake.
Log: correct debian rules
=> chore: correct debian rules

src/widgets/bottombar.cpp, src/widgets/ddropdownmenu.cpp
右下角显示文本在 paintEvent 中手动绘制，使用字体默认的英文字符高度，
但中英文字符在不同字体高度不同，导致计算错误，显示异常。
修改字符高度计算方式，调整为完整字符串的高度。
同时移除底栏设置的默认字体，保存与系统字体一致。
Log: 修复特定中文字体下，右下角显示字体不全的问题。
Bug: https://pms.uniontech.com/bug-view-187763.html
Influence: 底栏文件编码显示 底栏显示字体
=> fix: 修复特定中文字体下，右下角显示字体不全的问题。

src/widgets/window.cpp, src/widgets/window.h, tests/src/widgets/ut_window.cpp
Qt内部文本布局计算存在越界，完整文档高度可能返回负数，导致预览为空。
bug143359已有部分修改，此提交更新大文本预览调整文本高亮计算方式，
延后高亮处理。
Log: 修复文本编辑器大文件打印预览为空的问题
Bug: https://pms.uniontech.com/bug-view-67209.html
Influence: 大文件打印预览
=> fix: 修复文本编辑器大文件打印预览为空的问题

src/common/settings.cpp, src/editor/deletebackcommond.cpp, src/editor/deletetextundocommand.cpp, src/editor/dtextedit.cpp, src/editor/dtextedit.h, src/editor/inserttextundocommand.cpp, src/resources/settings.json, tests/src/editor/ut_textedit.cpp, translations/deepin-editor.ts, translations/deepin-editor_zh_CN.ts
文本编辑器部分计算采用 QTextCursor::NextCharacter 的方式计算偏移，
但单个字符可能占用多个偏移量，导致拷贝、黏贴、撤销等异常。
修改字符串计算方式，按字节偏移位置计算而非按显示字符数计算。
统一文档中的换行处理方式为 \n ，以保证偏移位置计算正常。
Log: 修复处理多字节编码文本时拷贝、撤销异常
Bug: https://pms.uniontech.com/bug-view-187765.html, https://pms.uniontech.com/bug-view-187773.html
Influence: 多字节编码文本拷贝、撤销
=> fix: 修复处理多字节编码文本时拷贝、撤销异常

src/editor/deletetextundocommand.cpp, src/editor/dtextedit.cpp, tests/src/editor/ut_textedit.cpp
删除撤销项使用 QTextCursor::position() 记录起始位置，
反向选取文本时 position() 记录的是尾部索引，
修改为 selectionStart() ， 以恢复准确光标位置。
Log: 修复撤销删除后位置错误的问题
Bug: https://pms.uniontech.com/bug-view-187773.html
Influence: 撤销删除
=> fix: 修复撤销删除后位置错误的问题

com.deepin.editor.policy
The old description is misleading as the code doesn't check or limit the write to /etc in any way. Let's make it "Save file with administrator privilege" for better correctness and transparency.
=> chore: improve policykit description & message

src/editor/dtextedit.cpp
文本编辑器序号显示使用单独字体，但计算宽度时未使用此字体计算,
导致显示绘制补全。调整计算序号宽度时使用指定字体，以正常显示。
Log: 修复使用特殊字体时，序号显示不全
Bug: https://pms.uniontech.com/bug-view-188417.html
Influence: 序号显示
=> fix: 修复使用特殊字体时，序号显示不全

src/encodes/detectcode.cpp, src/encodes/detectcode.h
根据GB18030-2022文档，调整自2005标准的变更字符。
还原为iconv（2022标准）加载，同时对部分UTF展示字符做映射表适配。
Log: 适配GB18030-2022规范兼容2005标准
Influence: 编码转换 GB18030显示 另存
=> feat: 适配GB18030-2022规范兼容2005标准

src/common/utils.cpp
判断标志初始化错误，导致在V20环境下无法进入DBus调用的分支，
无法唤起窗口。
Log: 修复最小化后，双击文件无法弹出编辑器窗口
Bug: https://pms.uniontech.com/bug-view-194029.html
Influence: 激活窗口
=> fix: 修复最小化后，双击文件无法弹出编辑器窗口

src/common/settings.cpp
设置界面中的字体选项和字号选项非同一布局，高分辨率下异常，
调整字体的 ComboBox 宽度设置，以保证在压缩对话框宽度时，
ComboBox 缩放和下方的 SpinBox 保持一致。
Log: https://pms.uniontech.com/bug-view-157559.html
Bug: 修复设置界面中字体和字号选项未对齐
Influence: 设置界面
=> fix: 修复设置界面中字体和字号选项未对齐

src/widgets/ddropdownmenu.cpp
屏幕缩放值获取错误，调整为获取当前屏幕缩放准确值
Log: 修复高分屏1.5缩放下图标模糊
Bug: https://pms.uniontech.com/bug-view-171749.html
Influence: 高分屏缩放显示
=> fix: 修复高分屏1.5缩放下图标模糊

debian/rules, debian/source/format, src/CMakeLists.txt, src/common/utils.h, src/thememodule/themelistmodel.cpp
Log: 优化玲珑适配代码
让 linglong 和 debian 都统一使用 CMAKE_INSTALL_PREFIX 设置安装前缀，并都设置 LINGLONG_PREFIX 宏（debian 下=/usr），避免不必要的分支
注意 CMAKE_INSTALL_PREFIX 默认值是 /usr/local， 如果需要修改默认值应该使用：
```
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
set(CMAKE_INSTALL_PREFIX /usr)
endif ()
```
而不应该使用现在的写法，这会忽略用户指定的 -DCMAKE_INSTALL_PREFIX 参数。
尽管可以将默认值设置为 /usr ，但仍然建议使用 `/usr/local`， 系统管理员通过 `make install` 应该使用的该路径而非/usr，只是系统仓库的包必须使用 /usr 而非 /usr/local，这应该在 debian/rules 设置
=> chore: remove redundant code for linglong

src/editor/dtextedit.cpp
fix: https://github.com/linuxdeepin/developer-center/issues/4203
修复了搜索功能在只存在与大小写不完全匹配的结果时，搜索结果展示情况不符合预期
=> fix: deepin-editor searching problem

src/editor/dtextedit.cpp, src/editor/editwrapper.cpp
文本重新高亮处理时，会导致文本块重新布局，和窗口大小变更时
导致的全文档重新布局存在计算冲突。调整文本高亮处理方式，
降低计算频率，已高亮的文本不再重复高亮，规避计算冲突。
Log: 修复部分格式高亮文本在窗口最大化状态下，文档不能完全显示
Bug: https://pms.uniontech.com/bug-view-172681.html
Influence: SyntaxHighlight
=> fix: Document in maximumized window is incomplete.

src/editor/deletebackcommond.cpp, src/editor/dtextedit.cpp, src/editor/inserttextundocommand.cpp, src/editor/inserttextundocommand.h, tests/src/editor/ut_textedit.cpp
拖拽文本包含删除及插入操作，顺序执行时操作的
文本偏移量会更新，修改为固定的偏移量。
更新拖拽插入部分UT，修复部分异常的UT。
Log: 修复重做拖拽文本操作时，操作的文本位置异常
Bug: https://pms.uniontech.com/bug-view-196349.html
Influence: DragText UnitTest
=> fix: Redo drag text error.

src/editor/dtextedit.cpp
修复重做从其它应用或标签页拖拽文本操作时，复位位置错误,
使用固定的偏移量计算复位位置。
Log: 修复重做从其它应用或标签页拖拽文本操作时，复位位置错误
Influence: DragText
=> fix: Redo drag text from other app error.

misc/configs/org.deepin.editor.json, src/common/config.cpp, src/common/config.h, src/encodes/detectcode.cpp
iconv底层适配GB18030-2022标准,回退上层应用GB18030修改。
添加DConfig配置是否使用上层修改补丁，当处于2005标准时
仍会强制使用上层修改补丁以适配2022标准。
Log: 回退GB18030修改
Influence: GB18030 Encoding
=> fix: Roll back gb18030 midification.

debian/changelog
Update version to 6.0.11
相关PR:
* https://github.com/linuxdeepin/deepin-editor/pull/253
* https://github.com/linuxdeepin/deepin-editor/pull/254
* https://github.com/linuxdeepin/deepin-editor/pull/255
* https://github.com/linuxdeepin/deepin-editor/pull/256
* https://github.com/linuxdeepin/deepin-editor/pull/257
Log: Update version to 6.0.11
=> chore: Update version to 6.0.11

debian/changelog
[linglong] Update version to 6.0.13
PR:
* https://github.com/linuxdeepin/deepin-editor/pull/261
* https://github.com/linuxdeepin/deepin-editor/pull/262
Log: [linglong] Update version to 6.0.13
=> chore: [linglong] Update version to 6.0.13

debian/changelog
Bump version to 6.0.14
PR:
* https://github.com/linuxdeepin/deepin-editor/pull/261
* https://github.com/linuxdeepin/deepin-editor/pull/262
* https://github.com/linuxdeepin/deepin-editor/pull/264
Log: Bump version to 6.0.14
=> chore: Bump version to 6.0.14

debian/changelog
Bump version to 6.0.15
PR:
* https://github.com/linuxdeepin/deepin-editor/pull/266
Log: Bump version to 6.0.15
=> chore: Bump version to 6.0.15

src/editor/dtextedit.cpp
Shortcuts Alt + P / N match the help Shortcuts Alt + P / N, left to right match,forbid to match the English quotation marksas brackets
Log: this "ALT + P/N" shortcut do not require the English quotation to be considered
Bug: https://pms.uniontech.com/bug-view-233883.html
fix: Shortcut 'Ctrl + M cursor' move to row indentation not implemented
change the logic of the 'Ctrl + M' Shortcut to a normal action.
log: Fix the Shortcut 'Ctrl + M cursor' to move to raw indentation
Bug: https://pms.uniontech.com/bug-view-233877.html
=> fix two Shortcuts with 'Alt + P/N' and 'Ctrl+M'

debian/changelog
Bump version to 6.0.16
PR:
* https://github.com/linuxdeepin/deepin-editor/pull/268
* https://github.com/linuxdeepin/deepin-editor/pull/269
* https://github.com/linuxdeepin/deepin-editor/pull/270
* https://github.com/linuxdeepin/deepin-editor/pull/271
Log: Bump version to 6.0.16
=> chore: Bump version to 6.0.16

src/widgets/window.cpp
调整默认快捷键浮窗弹出位置.
现在将显示在焦点屏幕(光标所在屏幕)中央.
Log: 调整默认快捷键浮窗弹出位置
Task: https://pms.uniontech.com/task-view-332267.html
Influence: Shortcuts
=> feat: Change default shortcuts popup position

src/editor/dtextedit.cpp, src/editor/dtextedit.h, tests/src/editor/ut_textedit.cpp
Change default search to be case insensitive,
affecting rind / replace / color mark.
变更默认字符查找不区分大小写, 影响查找/替换/颜色
标记功能.
Log: 变更默认字符查找不区分大小写
Bug: https://pms.uniontech.com/bug-view-262733.html
=> fix: Change default search to be case insensitive

src/editor/dtextedit.cpp
Change the setting when case sensitive.
调整区分大小写配置时的设置
Log: 修复错误的匹配大小写判断设置
Bug: https://pms.uniontech.com/bug-view-262733.html
=> fix: Wrong case sensitive config

debian/changelog
Bump version to 6.0.18
PR:
* https://github.com/linuxdeepin/deepin-editor/pull/280
* https://github.com/linuxdeepin/deepin-editor/pull/281
Log: Bump version to 6.0.18
=> chore: Bump version to 6.0.18

src/basepub/load_libs.c, src/common/utils.cpp, src/main.cpp, tests/src/common/ut_utils.cpp
Optimize startup failure problem
Log: Optimize startup failure problem
Task: https://pms.uniontech.com/task-view-361175.html
=> fix: Optimize startup failure problem

src/common/utils.h, src/editor/deletebackcommond.cpp, src/editor/deletebackcommond.h, src/editor/deletetextundocommand.cpp, src/editor/deletetextundocommand.h, src/editor/dtextedit.cpp, src/editor/dtextedit.h, src/editor/inserttextundocommand.cpp, src/editor/inserttextundocommand.h, tests/src/editor/ut_deletebackcommond.cpp, tests/src/editor/ut_deletetextundocommand.cpp, tests/src/editor/ut_inserttextundocommand.cpp, tests/src/editor/ut_textedit.cpp
[fix: crash when undoing column edit](https://github.com/linuxdeepin/deepin-editor/commit/bef96515048d757f2596d84f3dd7f6b60c76a589) 
Delete command stores temporary reference variable,
which will be empty when changing cursor.
Change storage variable type to store data persistently.
Log: Fix crash when undoing column edit
Bug: https://pms.uniontech.com/bug-view-273663.html
Influence: column-editing
[fix: restore column selection after undo](https://github.com/linuxdeepin/deepin-editor/commit/09b8dc3de7ec54c0e284b2faac05aacc637785a9) 
As title.
update backward / forward delete;
update unit test.
Log: Restore column selection after undo.
Bug: https://pms.uniontech.com/bug-view-273663.html
Influence: column-editing
[fix: cursor pos wrong after column …
=> fix: column editing and insert

src/editor/inserttextundocommand.cpp
The `alt` column flag return incorrect,
paste empty text.
Log: Fix can not paste after undo
Bug: https://pms.uniontech.com/bug-view-287523.html
Influence: undo-stack
=> fix: can not paste after undo

src/editor/editwrapper.cpp
In Qt5, just under 2^30 chcaacters in one QString. So we need catch bad_calloc and abort allocate.
Log: Fix one crash issue.
Bug: https://pms.uniontech.com/bug-view-297727.html
=> fix: crash when characters over 2^30

src/controls/warningnotices.cpp
See https://github.com/linuxdeepin/dtkwidget/pull/628 The DFloatingMessage not trigger close() now,
wait for DtkWidget integration.
Log: Toast cannot be closed.
Bug: https://pms.uniontech.com/bug-view-297669.html
=> fix: floating message cannot be closed

src/common/iflytek_ai_assistant.cpp, src/common/iflytek_ai_assistant.h, src/editor/editwrapper.cpp
As title. Show the Copilot page, inform users that they need to agree to the User Agreement.
Use QDBusInterface instead of QProcess to start uos-ai.
Log: Fix connot detect uos-ai installed.
Bug: https://pms.uniontech.com/bug-view-300549.html
=> fix: cannot detect uos-ai in linglong

src/common/utils.cpp
Add support cert file mime type.
Log: Add support cert file mime type.
Bug: https://pms.uniontech.com/bug-view-297967.html
=> fix: can not open crt file

src/editor/dtextedit.cpp
As title.
Log: enable mark on read-only mode.
Bug: https://pms.uniontech.com/bug-view-297981.htm!
=> fix: enable mark on read-only mode

src/controls/tabbar.cpp, src/editor/dtextedit.cpp, src/widgets/ddropdownmenu.cpp, src/widgets/window.cpp
[fix: text color not change with theme change](https://github.com/linuxdeepin/deepin-editor/commit/e8c71e32e1af129d4bb9b15f7ae76bc549b98d41) 
Manual setPalette() is not recommended for DTK under Qt6.
Disable setPalette(), updated automatically.
Log: fix a theme color issue.
Bug: https://pms.uniontech.com/bug-view-305473.html
[fix: crash on hover leave statusbar menu](https://github.com/linuxdeepin/deepin-editor/commit/60e146ddc382baecdbd3c74713eda61ef9e1187a) 
In Qt6, ensure proper matching between
QEvent types and QEvent instances.
Log: fix a crash issue.
=> fix: text color not change with theme change

src/common/utils.cpp
Change MIME type detection to use content-based matching for more accurate file type recognition
Add application/x-troff-man MIME type to supported file types list
This improves file type detection accuracy by examining file contents
rather than relying solely on file extensions.
Log: improve MIME type detection and add man page support
Bug: https://pms.uniontech.com//bug-view-314393.html
=> fix: improve MIME type detection and add man page support
